apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubesneakers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: frontend
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesneakers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubesneakers
  template:
    metadata:
      labels:
        app: kubesneakers
    spec:
      containers:
      - name: kubecontainer
        image: fedemerino/sneakers:1.0.0
        ports:
        - containerPort: 8080
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb+srv://fedemerino:J4TviI4yCVromdLr@backend.lfn4tu6.mongodb.net/ecommerce
        imagePullPolicy: Always
