const Errors = {
    ROUTING_ERROR: 1,
    AUTHENTICATION_ERROR: 2,
    AUTHORIZATION_ERROR: 3,
    VALIDATION_ERROR: 4,
    DATABASE_ERROR: 5,
    INTERNAL_ERROR: 6,
    NOT_FOUND_ERROR: 7,
    BAD_REQUEST_ERROR: 8,
    CONFLICT_ERROR: 9,
    UNAUTHORIZED_ERROR: 10,
    INVALID_TYPE_ERROR: 11,
    MISSING_FIELDS: 12
}

module.exports = { Errors }