paths:
  /api/products:
    get:
      summary: Retrieves all products from the database
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Page number.
          required: true
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Max number of products per page.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '500':
          description: Internal Server Error
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Products'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/requestBodies/Products'
        '500':
          description: Internal Server Error
  /api/products/{pid}:
    get:
      summary: Retrieves a product by ID from the database
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        '500':
          description: Internal Server Error
    put:
      summary: Update a product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Products'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/requestBodies/Products'
        '500':
          description: Internal Server Error
    delete:
      summary: Delete a product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Product ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/requestBodies/Products'
        '500':
          description: Internal Server Error
components:
  schemas:
    Products:
      type: object
      properties: 
        _id: 
          type: ObjectId
          description: Product ID (Mongo Auto Generated)
        title:
          type: string
          description: Product Name
          required: true
        description:
          type: string
          description: Product Description
          required: true
        code:
          type: string
          description: Product Code
          required: true
        price:
          type: number
          description: Product Price
          required: true
        status:
          type: boolean
          description: Product Status
          required: true
        stock:
          type: number
          description: Product Stock
          required: true
        category:
          type: string
          description: Product Category
          required: true
        thumbnail:
          type: Array
          description: Product Thumbnail
          required: true
        featured:
          type: boolean
          description: Product Featured
        created_at:
          type: Date
          description: Product Created At
      example:
        _id: 64629854ff89bc478236bfd2
        title: Nike SB Dunk High Pro
        description: Zapatillas de Moda para Hombre
        code: NIKESBDUNKHIGHPRO
        price: 75099
        status: true
        stock: 3
        category: shoes
        thumbnail: [
          /img/NIKESBDUNKHIGHPRO.png
        ]
        featured: true
  requestBodies:
    Products:
      type: object
      properties: 
        title:
          type: string
          description: Product Name
          required: true
        description:
          type: string
          description: Product Description
          required: true
        code:
          type: string
          description: Product Code
          required: true
        price:
          type: number
          description: Product Price
          required: true
        status:
          type: boolean
          description: Product Status
          required: true
        stock:
          type: number
          description: Product Stock
          required: true
        category:
          type: string
          description: Product Category
          required: true
        thumbnail:
          type: Array
          description: Product Thumbnail
          required: true
        featured:
          type: boolean
          description: Product Featured
      example:
        title: Nike SB Dunk High Pro
        description: Zapatillas de Moda para Hombre
        code: NIKESBDUNKHIGHPRO
        price: 75099
        status: true
        stock: 3
        category: shoes
        thumbnail: [
          /img/NIKESBDUNKHIGHPRO.png
        ]
        featured: true